name: AntiCivBreak
version: ${version}
main: com.nekozouneko.antiCivBreak.AntiCivBreak
api-version: '1.21'
depend:
  - packetevents

commands:
  civdebug:
    permission: anticivbreak.commands.civdebug
  civsimulate:
    permission: anticivbreak.commands.civsimulate

permissions:
  anticivbreak.commands.civdebug:
    default: op
  anticivbreak.commands.civsimulate:
    default: op
  anticivbreak.notify:
    default: op